SAML2 frontend+backend: support reloading metadata
IdentityPython/SATOSA pull request #370
Opened 2021-06-11 00:04 UTC by vladimir-mencl-eresearch

Using the reload_metadata method added into pysaml2 in IdentityPython/pysaml2#809, support reloading metadata when triggered via an externally exposed URL (as `/<module_name>/reload-metadata`)

This is off by default (URL not exposed) and needs to be explicitly enabled by setting the newly introduced config option `enable_metadata_reload` for the SAML modules to `true` (or `yes`).

The loaded config is already preserved in the modules, so can be easily used to provide a reference copy of the metadata configuration to the `reload_metadata` method.

This is implemented separately for the SAML2 Backend and SAML2 Frontend (applying to all three SAML2 Frontend classes).

This will complete the missing functionality identified in IdentityPython/pysaml2#808

### All Submissions:

* [Y] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [Y] Have you added an explanation of what problem you are trying to solve with this PR?
* [Y] Have you added information on what your changes do and why you chose this as your solution?
* [Not yet] Have you written new tests for your changes?
* [N/A] Does your submission pass tests?
* [X] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

2021-07-13 00:42 UTC, c00kiemon5ter requested changes
I've made some suggestions on the structure. Let me know what you think.

2021-07-13 00:42 UTC, c00kiemon5ter commented on src/satosa/base.py
> +
Add generic form

```suggestion

    def _reload_metadata(self, context, config):
        """
        Reload SAML metadata
        """
        logger.debug("Reloading metadata")
        res = self.idp.reload_metadata(copy.deepcopy(config))
        message = "Metadata reload %s" % ("OK" if res else "failed")
        status = "200 OK" if res else "500 FAILED"
        return Response(message=message, status=status)
```

2021-07-13 00:42 UTC, c00kiemon5ter commented on src/satosa/backends/saml2.py
> +        return Response(message=message, status=status)
use generic form

```suggestion
        config = self.config[SAMLBackend.KEY_SP_CONFIG][SAMLBackend.KEY_METADATA]
        return super()._reload_metadata(context, config)
```

2021-07-13 00:42 UTC, c00kiemon5ter commented on src/satosa/frontends/saml2.py
> +        return Response(message=message, status=status)
use generic form

```suggestion
        config = self.config[SAMLFrontend.KEY_IDP_CONFIG][SAMLFrontend.KEY_METADATA]
        return super()._reload_metadata(context, config)
```

2021-07-13 00:42 UTC, c00kiemon5ter commented on src/satosa/base.py
> +
The generic form has a different signature

```
    def _reload_metadata(self, context, config):
```

vs

```
    def _reload_metadata(self, context):
```

maybe `SAMLBackend._reload_metadata` and `SAMLFrontend._reload_metadata` should have a different name.

On the suggestions, I call `super()._reload_metadata` to differentiate the two. If they are renamed, we can call `self._reload_metadata(context, config)` directly.

2021-07-20 05:05 UTC, vladimir-mencl-eresearch commented
Hi @c00kiemon5ter ,

Thanks also for this review.

I agree with the motivation for a generic method - I myself wasn't so comfortable with duplicating the code between the two copies of `_reload_metadata` in `SAMLBackend` and `SAMLFrontend`.

The two methods have very few differences - but besides what they use as config, it's also what object they invoke `reload_metadata` on - `self.sp` vs. `self.idp`.

So the proposed change would not work for SP metadata updates - it would be calling `self.idp.reload_metadata`, and `self.idp` would not exist for an SP.

We could also go one step further and add an additional `target` parameter to the generic form (being `self.idp` or `self.sp`), or stick with the original form ...

I initially decided to do two separate methods, after considering what shape a generic one would have to take, but happy to implement that if you'd think that would work out better.

Cheers,
Vlad

2021-07-26 21:10 UTC, c00kiemon5ter commented
rebased and merged by b78ab3ee828c4774b83a5bf1a521208c4c2af084 and 206d55d9c951e0c3dc55f4517ae1320059fadead

2021-07-26 21:10 UTC, closed without merging